#!/bin/bash

declare -A dictionary

if [ $# -gt 2 ]
   then
      while read line; do 
      name=$(echo $line | cut -d " " -f1)
      ip=$(echo $line | cut -d " " -f2)
      dictionary[$name]="$ip"
      names+=($name)
      done < Rasp_Ip.txt
      for i in "$@"
         do
            array+=($i)
         done
         load=${array[0]}
         rasp_quant=$((${#array[@]}-2))
         save=${array[-1]}
	if [[ $2 = all ]]
	   then
	       for ((j=0;j<${#names[@]};j++))
                  do
                     scp -rP 22 -o StrictHostKeyChecking=no $load pi@${dictionary[${names[j]}]}:$save
                  done
         else
             for l in "${@:1:$rasp_quant+1}"
                do
                    [ ${dictionary[$l]+abc} ] && scp -rP 22 -o StrictHostKeyChecking=no $load pi@${dictionary[$l]}:$save
                done
         fi
else
    clear
    echo "ERROR!!! FOLLOW THE PATTERN"
    echo ""
    echo "./rasp_copy <file to send> rasp1 rasp2...all <place in raspi>"
fi